stages:
- build-library
- build-python
# - package-library
- package-python
- deploy-python

variables:
  DEBIAN_FRONTEND: noninteractive
  TEST_REPORT: $CI_PROJECT_DIR/test_report.xml
  TWINE_USERNAME: __token__
  TWINE_PASSWORD: $PYPI_ACCESS_TOKEN_MATTEORAGNI

#  ___      _ _    _   _    _ _                 _        
# | _ )_  _(_) |__| | | |  (_) |__ _ _ __ _ _ _(_)___ ___
# | _ \ || | | / _` | | |__| | '_ \ '_/ _` | '_| / -_|_-<
# |___/\_,_|_|_\__,_| |____|_|_.__/_| \__,_|_| |_\___/__/
#                                                        
build-ubuntu-18.04:
  stage: build-library
  tags:
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/ubuntu-1804:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON ..
  - cmake --build . --config Release

build-ubuntu-20.04:
  stage: build-library
  tags:
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/ubuntu-2004:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON ..
  - cmake --build . --config Release

build-ubuntu-22.04:
  stage: build-library
  tags:
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/ubuntu-2204:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON ..
  - cmake --build . --config Release

build-windows-10-x64:
  stage: build-library
  tags:
  - win
  script:
  - mkdir build
  - cd build
  - cmake -A x64 -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_FORCE_EIGEN_DOWNLOAD=ON ..
  - cmake --build . --config Release

#  ___      _ _    _   ___      _   _             
# | _ )_  _(_) |__| | | _ \_  _| |_| |_  ___ _ _  
# | _ \ || | | / _` | |  _/ || |  _| ' \/ _ \ ' \ 
# |___/\_,_|_|_\__,_| |_|  \_, |\__|_||_\___/_||_|
#                          |__/                   

build-py36-linux:
  stage: build-python
  tags: 
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/python-36:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  # Building
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  - cd ..
  # Testing
  - $PYTHON_BIN -m pytest --junitxml=$TEST_REPORT test
  variables:
    PYTHON_BIN: /usr/bin/python3.6
  artifacts:
    paths:
    - src_py/distrib
    reports:
      junit: $TEST_REPORT

build-py37-linux:
  stage: build-python
  tags: 
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/python-37:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  # Building
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  - cd ..
  # Testing
  - $PYTHON_BIN -m pytest --junitxml=$TEST_REPORT test
  variables:
    PYTHON_BIN: /usr/bin/python3.7
  artifacts:
    paths:
    - src_py/distrib
    reports:
      junit: $TEST_REPORT

build-py38-linux:
  stage: build-python
  tags: 
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/python-38:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  # Building
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  - cd ..
  # Testing
  - $PYTHON_BIN -m pytest --junitxml=$TEST_REPORT test
  variables:
    PYTHON_BIN: /usr/bin/python3.8
  artifacts:
    paths:
    - src_py/distrib
    reports:
      junit: $TEST_REPORT

build-py39-linux:
  stage: build-python
  tags: 
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/python-39:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  # Building
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  - cd ..
  # Testing
  - $PYTHON_BIN -m pytest --junitxml=$TEST_REPORT test
  variables:
    PYTHON_BIN: /usr/bin/python3.9
  artifacts:
    paths:
    - src_py/distrib
    reports:
      junit: $TEST_REPORT

build-py310-linux:
  stage: build-python
  tags: 
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/python-310:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  # Building
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  - cd ..
  # Testing
  - $PYTHON_BIN -m pytest --junitxml=$TEST_REPORT test
  variables:
    PYTHON_BIN: /usr/bin/python3.10
  artifacts:
    paths:
    - src_py/distrib
    reports:
      junit: $TEST_REPORT

build-py311-linux:
  stage: build-python
  tags: 
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/python-311:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  # Building
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN -DPYBIND_CHECKOUT="2.13.1" ..
  - cmake --build . --config Release
  - cd ..
  # Testing
  - $PYTHON_BIN -m pytest --junitxml=$TEST_REPORT test
  variables:
    PYTHON_BIN: /usr/bin/python3.11
  artifacts:
    paths:
    - src_py/distrib
    reports:
      junit: $TEST_REPORT

build-py312-linux:
  stage: build-python
  tags: 
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/python-312:latest
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  # Building
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN -DPYBIND_CHECKOUT="2.13.1" ..
  - cmake --build . --config Release
  - cd ..
  # Testing
  - $PYTHON_BIN -m pytest --junitxml=$TEST_REPORT test
  variables:
    PYTHON_BIN: /usr/bin/python3.12
  artifacts:
    paths:
    - src_py/distrib
    reports:
      junit: $TEST_REPORT

build-py36-win:
  stage: build-python
  tags: 
  - win
  script:
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_FORCE_EIGEN_DOWNLOAD=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  variables:
    PYTHON_BIN: C:\Python36\python.exe
  artifacts:
    paths:
    - src_py/distrib

build-py37-win:
  stage: build-python
  tags: 
  - win
  script:
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_FORCE_EIGEN_DOWNLOAD=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  variables:
    PYTHON_BIN: C:\Python37\python.exe
  artifacts:
    paths:
    - src_py/distrib

build-py38-win:
  stage: build-python
  tags: 
  - win
  script:
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_FORCE_EIGEN_DOWNLOAD=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  variables:
    PYTHON_BIN: C:\Python38\python.exe
  artifacts:
    paths:
    - src_py/distrib

build-py39-win:
  stage: build-python
  tags: 
  - win
  script:
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_FORCE_EIGEN_DOWNLOAD=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  variables:
    PYTHON_BIN: C:\Python39\python.exe
  artifacts:
    paths:
    - src_py/distrib

build-py310-win:
  stage: build-python
  tags: 
  - win
  script:
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_FORCE_EIGEN_DOWNLOAD=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN ..
  - cmake --build . --config Release
  variables:
    PYTHON_BIN: C:\Python310\python.exe
  artifacts:
    paths:
    - src_py/distrib

build-py311-win:
  stage: build-python
  tags: 
  - win
  script:
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_FORCE_EIGEN_DOWNLOAD=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN -DPYBIND_CHECKOUT="2.13.1" ..
  - cmake --build . --config Release
  variables:
    PYTHON_BIN: C:\Python311\python.exe
  artifacts:
    paths:
    - src_py/distrib

build-py312-win:
  stage: build-python
  tags: 
  - win
  script:
  - cd src_py
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_FORCE_EIGEN_DOWNLOAD=ON -DPYTHON_EXECUTABLE:FILEPATH=$PYTHON_BIN -DPYBIND_CHECKOUT="2.13.1" ..
  - cmake --build . --config Release
  variables:
    PYTHON_BIN: C:\Python312\python.exe
  artifacts:
    paths:
    - src_py/distrib

#  ___         _                   ___      _   _             
# | _ \__ _ __| |____ _ __ _ ___  | _ \_  _| |_| |_  ___ _ _  
# |  _/ _` / _| / / _` / _` / -_) |  _/ || |  _| ' \/ _ \ ' \ 
# |_| \__,_\__|_\_\__,_\__, \___| |_|  \_, |\__|_||_\___/_||_|
#                      |___/           |__/                   

package-python:
  stage: package-python
  image: docker-registry.antemotion.com/utils/docker-images/python-38:latest
  tags:
  - linux
  needs:
  - job: build-py36-linux
    artifacts: true
  - job: build-py37-linux
    artifacts: true
  - job: build-py38-linux
    artifacts: true
  - job: build-py39-linux
    artifacts: true
  - job: build-py310-linux
    artifacts: true
  - job: build-py311-linux
    artifacts: true
  - job: build-py312-linux
    artifacts: true
  - job: build-py36-win
    artifacts: true
  - job: build-py37-win
    artifacts: true
  - job: build-py38-win
    artifacts: true
  - job: build-py39-win
    artifacts: true
  - job: build-py310-win
    artifacts: true
  - job: build-py311-win
    artifacts: true
  - job: build-py312-win
    artifacts: true
  script:
  - cd src_py/distrib/G2lib
  - python3 setup.py sdist
  artifacts:
    paths:
    - src_py/distrib/G2lib

deploy-python:
  stage: deploy-python
  image: docker-registry.antemotion.com/utils/docker-images/python-38:latest
  tags:
  - linux
  needs:
  - job: package-python
    artifacts: true
  before_script:
  - python3 -m pip install -U twine
  script:
  - cd src_py/distrib/G2lib
  - python3 -m twine upload dist/*
  only:
  - tags

  
  
