variables:
  CMAKE_BUILD_TYPE: RelWithDebInfo
  DEBIAN_FRONTEND: noninteractive

build-ubuntu-18.04:
  tags:
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/ubuntu-1804
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON ..
  - cmake --build .

build-ubuntu-20.04:
  tags:
  - linux
  image: docker-registry.antemotion.com/utils/docker-images/ubuntu-2004
  before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends --no-install-suggests liblapack-dev gfortran coinor-libipopt-dev libeigen3-dev
  script:
  - mkdir build
  - cd build
  - cmake -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON ..
  - cmake --build .

build-windows-10-x64:
  tags:
  - win
  script:
  - mkdir build
  - cd build
  - cmake -A x64 -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON ..
  - cmake --build .

