name: build-libraries
on:
 - push
jobs:
  build-ubuntu-1804-x64:
    runs-on: ubuntu-18.04
    steps:
     - uses: actions/checkout@v3
       name: Checkout Repository
     - run: apt-get install -y --no-install-recommends --no-install-suggests coinor-libipopt-dev libeigen3-dev
     - run: mkdir build && cd build && cmake -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON ..
  build-ubuntu-2004-x64:
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v3
       name: Checkout Repository
     - run: apt-get install -y --no-install-recommends --no-install-suggests coinor-libipopt-dev libeigen3-dev
     - run: mkdir build && cd build && cmake -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=ON ..
  build-windows-x64:
    runs-on: windows-server
    steps:
     - uses: actions/checkout@v3
       name: Checkout Repository
     - run: mkdir build && cd build && cmake -Ax64 -DCLOTHOIDS_BUILD_SHARED=ON -DCLOTHOIDS_ENABLE_EIGEN_SOLVER=ON -DCLOTHOIDS_ENABLE_IPOPT_SOLVER=OFF ..
